todo/todo/urls.py
from django.contrib import admin
from django.urls import path,include
from WebApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.App),
    path("edit/<id>",views.edit, name="edit")
]

todo/WebApp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    selecte = ( ('OPEN', 'Open'),
                ('WORKING', 'Working'),
                ('DONE', 'Done'),
                ('OVERDUE', 'Overdue'))
    
    title=models.CharField(max_length=100,blank=False,null=False)
    description = models.CharField(max_length=1000, blank=False, null=False)
    due_date = models.DateField(blank=True,null=True)
    status = models.CharField(choices=selecte, default="open",max_length=10,blank=False)
    timestamp = models.DateTimeField(auto_now_add=True) 
    
    def __str__(self):
        return self.title
    

todo/WebApp/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title","description","due_date","status"]
        
         
class  UpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title","description","due_date","status"]
        
   

todo/WebApp/views.py
from django.shortcuts import render, HttpResponse ,redirect
from .models import Task
from .forms import TaskForm,UpdateForm

# Create your views here.

def App(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home:App")
    
    tasks = Task.objects.all()
    form = TaskForm()
    print(form)
    
    return render(request, 'home.html', {"tasks":tasks})


def edit(request,id=id):
    task = Task.objects.get(id=id)
    if request.method == "POST":
        form = UpdateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home:App")
    
    form = UpdateForm(request.POST or None )
    print(form)
    
    return render(request, 'edit.html', {"form": form})

todo/templates/edit.html
 {% extends 'home.html' %}

 {% block content %}
 <div class="container">
    <div class="row justify-content-center">
        <div class='col-sm-7'>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Update">
            </form>
        </div>
    </div>
</div>

 {% endblock %}

todo/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Django Todo</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class='col-sm-7'>

  <form method="POST">
    {% csrf_token %}
    <div class="container my-3">
        <h2 class='text-center'>Welcome to ToDos list - Add a Task</h2>

    </div>
    <div class="form-group">
    <th><label for="id_title">Title:</label></th>
    <td>

      <input type="text" name="title" maxlength="100" required id="id_title">


    </td>


  </tr>
</div>
  <div class="form-group">
    <tr>
        <th><label for="id_description">Description:</label></th>
        <td>
    
          <input type="text" name="description" maxlength="1000" required id="id_description">    
    
    
        </td>
      </tr>
    </div>
    <div class="form-group">
    <tr>
        <th><label for="id_due_date">Due date:</label></th>
        <td>
    
          <input type="date" name="due_date" id="id_due_date">
    
    
        </td>
      </tr>
    </div>
     <div class="form-group">
        <tr>
        <th><label for="id_status">Status:</label></th>
    
    <td>

      <select name="status" id="id_status">
  <option value="OPEN">Open</option>

  <option value="WORKING">Working</option>

  <option value="DONE">Done</option>

  <option value="OVERDUE">Overdue</option>

</select>




    </td>
   </tr>
      </div>
     
    <button type="submit" class="btn btn-dark">Submit</button>
  </form>
</div>

</div>

</div> 
 <table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Task</th>
            <th scope="col">Desecription</th>
            <th scope="col">Due Date</th>
            <th scope="col">status</th>
        </tr>
    </thead>
    <tbody>
    <div> 
  {% comment %} <table class="table"> {% endcomment %}
    {% comment %} <thead> {% endcomment %}
        <tbody>
            {% for task in tasks %}
                <tr>
                    <td scope='row'>{{ forloop.counter }}</td>
                    <td scope='row'> {{ task.title}}</td>
                    <td scope="row"> {{ task.description }}</td>
                    <td scope="row"> {{ task.due_date }}</td>
                    <td scope='row'> {{ task.status }}</td>
                    <td><a href=""><i class="fa fa-edit text-primary"></i></a></td>
                </tr>
            {% endfor %}
        </tbody>
    {% comment %} </thead>
  </table> {% endcomment %}
</div> 
</body>
</html>